# Starter pipeline
- task: CmdLine@2
  inputs:
    script: 'java -jar prpc-service-utils.jar -inputFile=myInput.xml -outputFile=myOutput.xml'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
- task: CmdLine@2
  inputs:
    script: './config.sh --url https://dev.azure.com/{organization} --auth pat --token {personal_access_token} --pool {agent_pool_name} --agent {agent_name} –work  _workork'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script:
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
